------------ACTIVIDAD 4.1------------------
CREATE OR REPLACE TYPE ESTADISTICAS_ARRAY AS ARRAY(4) OF FLOAT;
-------------------------------------------
CREATE TABLE ESTADISTICAS_JUGADOR(
ID_EST INT PRIMARY KEY,
ID_JUGADOR NUMBER,
TEMPORADA INT,
ESTADISTICAS ESTADISTICAS_ARRAY,
FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES(ID_JUG)
);
-------------------------------------------
CREATE OR REPLACE TYPE JUGADOR AS OBJECT(
ID_JUG NUMBER,
ID_EQUIPO NUMBER,
NOMBRE VARCHAR2(100),
PROCEDENCIA VARCHAR2(100),
ALTURA VARCHAR2(100),
PESO VARCHAR2(100),
POSICION VARCHAR2(100)
)
-------------------------------------------
CREATE TABLE JUGADORES OF JUGADOR(
ID_JUG PRIMARY KEY,
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
);
-------------------------------------------
CREATE OR REPLACE TYPE EQUIPO AS OBJECT(
ID_EQUIPO NUMBER,
NOMBRE VARCHAR2(100),
CIUDAD VARCHAR2(100),
COMFERENCIA VARCHAR2(100),
DIVISION VARCHAR2(100)
)
-------------------------------------------
CREATE TABLE EQUIPOS OF EQUIPO(
ID_EQUIPO PRIMARY KEY
);
-------------------------------------------
CREATE OR REPLACE TYPE PARTIDO AS OBJECT(
CODIGO NUMBER,
ID_EQUIPO_LOCAL NUMBER,
ID_EQUIPO_VISITANTE NUMBER,
PUNTOS_LOCAL NUMBER,
PUNTOS_VISITANTE NUMBER,
TEMPORADA NUMBER
);
-------------------------------------------
CREATE TABLE PARTIDOS OF PARTIDO(
CODIGO PRIMARY KEY,
FOREIGN KEY (ID_EQUIPO_LOCAL) REFERENCES EQUIPOS(ID_EQUIPO),
FOREIGN KEY (ID_EQUIPO_VISITANTE) REFERENCES EQUIPOS(ID_EQUIPO)
);

-------------------------------------------
------Departamentos-Empleados--------------
-------------------------------------------
CREATE OR REPLACE TYPE persona_obj AS OBJECT(
  nombre VARCHAR2(10),
  apellidos VARCHAR2(20),
  fnacimiento DATE
);
--------------------------------------------
CREATE TYPE personaNT AS TABLE OF persona_obj;
--------------------------------------------
CREATE TABLE empleados(
CODIGO NUMBER PRIMARY KEY,
OFICIO VARCHAR2(100),
DIR NUMBER,
FECHA DATE,
SALARIO NUMBER,
COMISION NUMBER,
persona personaNT,
ID_DEPARTAMENTO NUMBER,
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEP)
)NESTED TABLE persona STORE AS personas_tab;
----------------------------------------------
CREATE TABLE DEPARTAMENTOS(
ID_DEP NUMBER PRIMARY KEY,
NOMBRE_DEPARTAMENTO VARCHAR2(100),
LOC VARCHAR2(100)
);
